### ------- PROFILE page req and res check -------

### Get Header Details
GET http://localhost:3001/index/allPosts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMzk3MDIyOSwiZXhwIjoxNzEzOTk5MDI5fQ.v-l5EVMtHXP7VybPeMGM8IKq6UuYg60E101nJRiIXYE
