#Get a Post Specific Details
GET http://localhost:3001/allposts/getAllPosts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMzg1NzIyNiwiZXhwIjoxNzEzODg2MDI2fQ.4KuBR077yliFhI7FWiR2jJLIf8eo8FwNVxsw60MuBQk



