### Get Header Details
GET http://localhost:3001/profile/headerDetails
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjc1MTg5MiwiZXhwIjoxNzEyNzU1NDkyfQ.glNGLcf02mmZoGRf-kBfGP8gHtpo-31JrDJ7OMtDPsk

### Get Traveler Stats Details
GET http://localhost:3001/profile/travelerStats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjc1MTg5MiwiZXhwIjoxNzEyNzU1NDkyfQ.glNGLcf02mmZoGRf-kBfGP8gHtpo-31JrDJ7OMtDPsk


### GET User Details (To From Control)
GET http://localhost:3001/profile/getUserDetails
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjc1NjIxNiwiZXhwIjoxNzEyNzU5ODE2fQ.4unBODQqjm2TTWuLDtDqrfNiDHziq40jxsZp1N2GO8I


### Update User Details (From From Control)
POST http://localhost:3001/profile/saveNewUserDetails
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjc1MTg5MiwiZXhwIjoxNzEyNzU1NDkyfQ.glNGLcf02mmZoGRf-kBfGP8gHtpo-31JrDJ7OMtDPsk

{
  "username":"123",
  "password":"123",
  "bio":"Bio 123"
}